/* USER CODE BEGIN Header */
/**
 ******************************************************************************
 * @file    main.c
 * @brief   RPOD IMU-UART Test — Blue Pill (STM32F103C8T6)
 *          Reads MPU6050 via I2C1 (PB6/PB7)
 *          Sends IMU data over USART2 (PA2/PA3) at 115200 baud
 ******************************************************************************
 */
/* USER CODE END Header */

#include "main.h"
#include "i2c.h"
#include "usart.h"
#include "gpio.h"
#include "imu.h"
#include <stdio.h>
#include <string.h>

/* --- Global variables (watchable in Live Expressions) --- */
volatile uint8_t  imu_ok     = 0;
volatile float    accel_x    = 0.0f;
volatile float    accel_y    = 0.0f;
volatile float    accel_z    = 0.0f;
volatile float    gyro_x     = 0.0f;
volatile float    gyro_y     = 0.0f;
volatile float    gyro_z     = 0.0f;
volatile uint32_t tx_count   = 0;   /* increments every successful send */

/* --- Packet format sent over UART ---
 * ASCII CSV for easy debugging:
 * "IMU,ax,ay,az,gx,gy,gz,ok\r\n"
 * e.g. "IMU,+0.031,+0.002,+9.812,+0.11,-0.03,+0.22,1\r\n"
 *
 * Once the Jetson ROS2 serial bridge is ready, swap to binary struct.
 */

static char tx_buf[128];

static char *format_fixed(char *buf, size_t len, float value)
{
    int32_t scaled = (int32_t)(value * 1000.0f + (value >= 0.0f ? 0.5f : -0.5f));
    int negative = (scaled < 0);
    if (negative) scaled = -scaled;
    int32_t whole = scaled / 1000;
    int32_t frac  = scaled % 1000;
    if (frac < 0) frac = -frac;

    int written = snprintf(buf, len, "%c%ld.%03ld", negative ? '-' : '+', (long)whole, (long)frac);
    if (written < 0 || (size_t)written >= len)
    {
        return buf + len;
    }
    return buf + written;
}

void SystemClock_Config(void);

int main(void)
{
    /* HAL init */
    HAL_Init();
    SystemClock_Config();

    /* Peripheral init (generated by CubeMX) */
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();

    /* Status LED on PC13 — HIGH = off on Blue Pill (active low) */
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);

    /* --- IMU Init --- */
    HAL_Delay(100);   /* let MPU6050 power stabilise */

    if (IMU_Init(&hi2c1) == HAL_OK)
    {
        imu_ok = 1;
        /* Three quick blinks = IMU found */
        for (int i = 0; i < 3; i++) {
            HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);
            HAL_Delay(100);
            HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);
            HAL_Delay(100);
        }
    }
    else
    {
        imu_ok = 0;
        /* Ten slow blinks = IMU not found — check SDA/SCL wiring */
        for (int i = 0; i < 10; i++) {
            HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);
            HAL_Delay(300);
            HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);
            HAL_Delay(300);
        }
    }

    /* --- Main loop: read IMU @ ~50 Hz, send over UART --- */
    IMUData_t imu_data;

    while (1)
    {
        if (imu_ok)
        {
            if (IMU_Read(&imu_data) == HAL_OK)
            {
                /* Copy to globals so Live Expressions can see them */
                accel_x = imu_data.accel_x;
                accel_y = imu_data.accel_y;
                accel_z = imu_data.accel_z;
                gyro_x  = imu_data.gyro_x;
                gyro_y  = imu_data.gyro_y;
                gyro_z  = imu_data.gyro_z;

                /* Build ASCII CSV packet with fixed-point formatting.
                 * Avoid float formatting dependency in nano.specs builds.
                 */
                char *p = tx_buf;
                char *end = tx_buf + sizeof(tx_buf);

                p += snprintf(p, end - p, "IMU,");
                p = format_fixed(p, end - p, accel_x);
                p += snprintf(p, end - p, ",");
                p = format_fixed(p, end - p, accel_y);
                p += snprintf(p, end - p, ",");
                p = format_fixed(p, end - p, accel_z);
                p += snprintf(p, end - p, ",");
                p = format_fixed(p, end - p, gyro_x);
                p += snprintf(p, end - p, ",");
                p = format_fixed(p, end - p, gyro_y);
                p += snprintf(p, end - p, ",");
                p = format_fixed(p, end - p, gyro_z);
                p += snprintf(p, end - p, ",%u\r\n", (unsigned)imu_ok);
                int len = (int)(p - tx_buf);

                if (len > 0)
                {
                    HAL_UART_Transmit(&huart2, (uint8_t*)tx_buf, len, 10);
                    tx_count++;
                }

                /* Heartbeat blink every 100 packets (~2 sec) */
                if (tx_count % 100 == 0) {
                    HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
                }
            }
            else
            {
                /* Read failure — attempt re-init immediately and on every retry.
                 * Keep imu_ok false until the IMU is reachable again.
                 */
                imu_ok = 0;
                HAL_Delay(500);
                if (IMU_Init(&hi2c1) == HAL_OK)
                {
                    imu_ok = 1;
                }
            }
        }
        else
        {
            static uint32_t next_retry_ms = 0;
            uint32_t now = HAL_GetTick();

            if (now >= next_retry_ms)
            {
                next_retry_ms = now + 1000;
                if (IMU_Init(&hi2c1) == HAL_OK)
                {
                    imu_ok = 1;
                }
            }
        }

        HAL_Delay(20);  /* 50 Hz */
    }
}

/**
  * @brief System Clock Configuration — HSI × 16 = 64 MHz
  *        (No HSE crystal on most Blue Pill boards)
  */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState       = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState   = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource  = RCC_PLLSOURCE_HSI_DIV2;
    RCC_OscInitStruct.PLL.PLLMUL     = RCC_PLL_MUL16;  /* 4MHz × 16 = 64MHz */
    HAL_RCC_OscConfig(&RCC_OscInitStruct);

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;   /* HCLK  = 64 MHz */
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;     /* PCLK1 = 32 MHz (max 36) */
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;     /* PCLK2 = 64 MHz */
    HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2);
}

/* Required by printf via semihosting (optional) */
void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}
