/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "DIO_interface.h"
#include "RCC_interface.h"
#include "USART_INTERFACE.h"
#include "STD_types.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(u16 time);

int main(void)
{
	// initialize the system clock
	RCC_voidInitSysClock();
	// enable clock for GPIOC and AFIO
    RCC_voidDisableClock(RCC_APB2, 0);   // AFIO clock
    RCC_voidDisableClock(RCC_APB2, 2);   // GPIOA clock
	// set pin direction 13 in port C as output
    DIO_voidSetPinDirection(GPIOC,PIN13,OUTPUT_SPEED_50MHZ_PP);
	// initialize USART1
    MUSART_VidInit();
	/* Loop forever */
	while (1)
	{
		MUSART1_VidSendStringSynch("HELP");
	}
}

void delay(u16 time)
{

	for (int i = 0; i < time; i++)
	{
		for (int j = 0; j < time; j++)
		{
			asm("NOP");
		}
	}
}
